CREATE DATABASE Biblioteca;
GO
USE Biblioteca;

CREATE TABLE Libro
(
	IdLibro VARCHAR(10) NOT NULL,
	Titulo VARCHAR(40) NOT NULL,
	SubTitulo VARCHAR(40),
	Editorial VARCHAR(40) NOT NULL,
	Area VARCHAR(30) NOT NULL,
	AnioPublicacion CHAR(4) NOT NULL,
	TotalPaginas INT NOT NULL,
	Edicion VARCHAR(10) NOT NULL,
  
	CONSTRAINT PKLibro PRIMARY KEY(IdLibro)
);
GO

CREATE TABLE Autor
(
	IdAutor VARCHAR(10) NOT NULL,
	Nombre VARCHAR(40) NOT NULL,
	Nacionalidad VARCHAR(40) DEFAULT 'Desconocida',

	CONSTRAINT PKAutor PRIMARY KEY(IdAutor),
);
GO

CREATE TABLE Autoria
(
	IdAutor VARCHAR(10) NOT NULL,
	IdLibro VARCHAR(10) NOT NULL,

	CONSTRAINT PKAutoria PRIMARY KEY(IdAutor, IdLibro),
	CONSTRAINT FKAutor FOREIGN KEY(IdAutor) REFERENCES Autor ON DELETE CASCADE,
	CONSTRAINT FKLibros FOREIGN KEY(IdLibro) REFERENCES Libro ON DELETE CASCADE
);